import '@fontsource/poppins';
import '@fontsource/poppins/300.css';
import '@fontsource/poppins/600.css';
import { ChakraProvider } from '@chakra-ui/react';
import Head from 'next/head';
import React from 'react';

import theme from 'theme';

export default function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Gainimpact Chat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ChakraProvider theme={theme}>
        <Component {...pageProps} />
      </ChakraProvider>
    </>
  );
}
